apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      #            - name: mysql-persistent-storage
      #              mountPath: /var/lib/mysql
      volumes:
        #        - name: mysql-persistent-storage
        #          persistentVolumeClaim:
        #            claimName: mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-configmap